# Dockerfile References: https://docs.docker.com/engine/reference/builder/

# Start from golang:1.12-alpine base image
FROM nginx:1.19.6-alpine

# Copy default.conf
COPY ./conf.d/default.conf /etc/nginx/conf.d/default.conf
